### ISSUE TITLE
Invalid data received when no printer is connected. 

### ISSUE THREAD

**Issue by EdwardChamberlain** [synman/bambu-printer-manager#3]
When a connection to a printer fails invalid data is returned. For example: 
```py
print(printer.bed_temp)
> 0.0
```
This is because my access code is incorrect and the library can not successfully connect but it does not raise an error on the connection. 

Code to reproduce:
```py
config = BambuConfig(hostname="192.168.1.51", access_code="1234", serial_number="5678")
printer = BambuPrinter(config=config)
printer.start_session()
time.sleep(1)
print(printer.bed_temp)
```

The line where the program connects `printer.start_session()` should raise an error if the connection is unsuccessful

**Comment by synman** [comment]
There are a couple properties you can check for ensuring data integrity that I haven't fully documented yet, and are a work in progress (subject to change).

With v0.1.3 (released just last night) you'll find a new boolean property called `recent_data`.  

There is also a (currently) internal property I may expose called `_internalException` that will not be `None` if the connection is in a bad state.

I would say for now to rely on `recent_data` and rest assured this is something under further consideration as I require data quality in my own client use case.

**Comment by synman** [comment]
> When a connection to a printer fails invalid data is returned. For example: 
> ```py
> print(printer.bed_temp)
> > 0.0
> ```
> This is because my access code is incorrect and the library can not successfully connect but it does not raise an error on the connection. 
> 
> Code to reproduce:
> ```py
> config = BambuConfig(hostname="192.168.1.51", access_code="1234", serial_number="5678")
> printer = BambuPrinter(config=config)
> printer.start_session()
> time.sleep(1)
> print(printer.bed_temp)
> ```
> 
> The line where the program connects `printer.start_session()` should raise an error if the connection is unsuccessful

Here is the documentation (in the README) for using the `on_update` callback.

`on_update` (setter only)
Set a callback method that is invoked whenever new data is received from the printer.  Your `BambuPrinter` instance is passed into your callback method for convienence.

Example:
```py
def on_update(printer):

    print(f"tool=[{round(printer.tool_temp, 1)}/{round(printer.tool_temp_target, 1)}] " +
          f"bed=[{round(printer.bed_temp, 1)}/{round(printer.bed_temp_target, 1)}] " + 
          f"fan=[{parseFan(printer.fan_speed)}] print=[{printer.gcode_state}] speed=[{printer.speed_level}] " +
          f"light=[{'on' if printer.light_state else 'off'}]")
    
    print(f"stg_cur=[{parseStage(printer.current_stage)}] file=[{printer.gcode_file}] " +
          f"layers=[{printer.layer_count}] layer=[{printer.current_layer}] " +
          f"%=[{printer.percent_complete}] eta=[{printer.time_remaining} min] " +
          f"spool=[{printer.active_spool} ({printer.spool_state})]")

printer.on_update = on_update
```

**Comment by synman** [comment]
One last piece of info I will share for now is that throwing an exception is NOT the ideal course.  

Perhaps there are some edge cases, you mentioned one such as a bad access_code, but this is an abnormal state and you'll definitely know about it because it is logged to both $stderr and the BambuPrinter log file as a warning.

My intent is to provide an asynchronous communication library that handles all the underlying connectivity issues and recovers from them automatically.

And if you want to know how it is doing, it exposes some properties (mentioned previously) that inform you of things that matter.

**Comment by EdwardChamberlain** [comment]
The on_update callback is very useful and saves me having to poll the printer object in a while loop - thats a great idea.

> One last piece of info I will share for now is that throwing an exception is NOT the ideal course.

On reflection I can see both sides of this: your module is behaving similarly to the way `requests` handle errant status codes which is a different approach to what I was expecting but not really "wrong". I approached this much more synchronously than you had intended and was expecting to catch and handle the connection error myself. The benefit to what you have here is that I can leave my script running and it is indifferent to my printer being switched on and off. 

I'll rely on the `state` for now.

**Comment by synman** [comment]
> The on_update callback is very useful and saves me having to poll the printer object in a while loop - thats a great idea.
> 
> > One last piece of info I will share for now is that throwing an exception is NOT the ideal course.
> 
> On reflection I can see both sides of this: your module is behaving similarly to the way `requests` handle errant status codes which is a different approach to what I was expecting but not really "wrong". I approached this much more synchronously than you had intended and was expecting to catch and handle the connection error myself. The benefit to what you have here is that I can leave my script running and it is indifferent to my printer being switched on and off. 
> 
> I'll rely on the `state` for now. 

Great to read you found a path forward.  I'm going to keep this issue open for visibility / additional feedback for now.
